// مخطط المفارجة (الأنساب) — جداول/دوال/سياسات ببادئة almfrje_ على قاعدة alaoufi.me.
// مصدر واحد مشترك بين /api/migrate و /api/almfrje-setup (تفادياً للتكرار).
// كل الأوامر IF NOT EXISTS / OR REPLACE فيمكن تنفيذها مراراً بأمان.
export const ALMFRJE_SCHEMA_SQL = `
      CREATE EXTENSION IF NOT EXISTS pg_trgm;

      -- 1) الفروع
      CREATE TABLE IF NOT EXISTS public.almfrje_branches (
        id          bigint generated always as identity primary key,
        name        text not null,
        root_id     bigint,
        manager_id  uuid references auth.users(id) on delete set null,
        notes       text default '',
        created_at  timestamptz not null default now());

      -- 2) الأعضاء والصلاحيات
      CREATE TABLE IF NOT EXISTS public.almfrje_members (
        user_id    uuid primary key references auth.users(id) on delete cascade,
        full_name  text, username text, phone text,
        role       text not null default 'viewer' check (role in ('admin','branch_manager','viewer')),
        branch_id  bigint references public.almfrje_branches(id) on delete set null,
        is_active  boolean not null default false,
        perms      jsonb not null default '{}'::jsonb,
        created_at timestamptz not null default now());
      CREATE UNIQUE INDEX IF NOT EXISTS almfrje_members_phone_key
        ON public.almfrje_members (phone) WHERE phone IS NOT NULL AND phone <> '';
      CREATE UNIQUE INDEX IF NOT EXISTS almfrje_members_username_key
        ON public.almfrje_members (lower(username)) WHERE username IS NOT NULL AND username <> '';
      -- إشراف على عدّة فروع: مصفوفة معرّفات الفروع (تُضاف على القواعد القائمة أيضاً)
      ALTER TABLE public.almfrje_members ADD COLUMN IF NOT EXISTS branch_ids jsonb not null default '[]'::jsonb;
      -- موافقة الخصوصية عند التسجيل الذاتي: نشر الجوال في دليل الموقع أم استخدامٌ للموقع فقط
      ALTER TABLE public.almfrje_members ADD COLUMN IF NOT EXISTS phone_public boolean not null default false;
      -- ربط العضو بشخصه في الشجرة (يُحفظ تلقائياً عند إنشاء الحساب من المنتقي) —
      -- منه يُعرف فرعه الحقيقي (للمتواجدين وغيرها) دون تخمين.
      ALTER TABLE public.almfrje_members ADD COLUMN IF NOT EXISTS person_id bigint references public.almfrje_persons(id) on delete set null;
      -- توسيع أدوار العضو لتشمل «مشرف عام» (تُطبَّق على القواعد القائمة أيضاً)
      ALTER TABLE public.almfrje_members DROP CONSTRAINT IF EXISTS almfrje_members_role_check;
      ALTER TABLE public.almfrje_members ADD CONSTRAINT almfrje_members_role_check CHECK (role IN ('admin','general_manager','branch_manager','viewer'));

      -- 3) الأشخاص (الشجرة)
      CREATE TABLE IF NOT EXISTS public.almfrje_persons (
        id          bigint generated always as identity primary key,
        name        text not null,
        father_id   bigint references public.almfrje_persons(id) on delete set null,
        branch_id   bigint references public.almfrje_branches(id) on delete set null,
        generation  int  not null default 1,
        sex         text not null default 'male'  check (sex in ('male','female')),
        status      text not null default 'alive' check (status in ('alive','dead')),
        birth text default '', death text default '', phone text default '',
        email text default '', city text default '', photo_url text default '',
        notes text default '', sort int not null default 0,
        created_at  timestamptz not null default now(),
        created_by  uuid default auth.uid());
      -- أعمدة التتبّع (من أضاف/عدّل) — تُضاف على القواعد القائمة أيضاً
      ALTER TABLE public.almfrje_persons ADD COLUMN IF NOT EXISTS created_by_name text default '';
      ALTER TABLE public.almfrje_persons ADD COLUMN IF NOT EXISTS updated_by_name text default '';
      ALTER TABLE public.almfrje_persons ADD COLUMN IF NOT EXISTS updated_at timestamptz;
      ALTER TABLE public.almfrje_persons ADD COLUMN IF NOT EXISTS work text default '';
      ALTER TABLE public.almfrje_persons ADD COLUMN IF NOT EXISTS birthplace text default '';
      ALTER TABLE public.almfrje_persons ADD COLUMN IF NOT EXISTS nickname text default '';
      -- تتبّع آخر من عدّل كل حقل على حدة: { "city": {"by":"...","at":"..."}, ... }
      ALTER TABLE public.almfrje_persons ADD COLUMN IF NOT EXISTS field_audit jsonb not null default '{}'::jsonb;
      -- اجعل المعرّفات قابلةً للإدخال الصريح (لاستعادة النسخ الاحتياطية مع حفظ العلاقات)
      -- (almfrje_documents يُعالَج بعد إنشائه أدناه لأن جدوله يُنشأ لاحقاً)
      ALTER TABLE public.almfrje_persons   ALTER COLUMN id SET GENERATED BY DEFAULT;
      ALTER TABLE public.almfrje_branches  ALTER COLUMN id SET GENERATED BY DEFAULT;
      CREATE INDEX IF NOT EXISTS almfrje_persons_father_idx ON public.almfrje_persons(father_id);
      CREATE INDEX IF NOT EXISTS almfrje_persons_branch_idx ON public.almfrje_persons(branch_id);
      CREATE INDEX IF NOT EXISTS almfrje_persons_gen_idx    ON public.almfrje_persons(generation);
      CREATE INDEX IF NOT EXISTS almfrje_persons_name_trgm  ON public.almfrje_persons using gin (name gin_trgm_ops);
      -- حاجز القاعدة ضد تكرار اسم ابنٍ حيٍّ لنفس الأب (طبقة ثانية تحت فحص الواجهة).
      -- بمطابقة مُطبَّعة (توحيد الهمزات/الياء/الهاء وإزالة المسافات). وإن وُجدت تكراراتٌ
      -- قديمة تمنع إنشاءه، يُتجاهَل بصمت ولا يُعطَّل سير الترقية.
      DO $func$ BEGIN
        CREATE UNIQUE INDEX IF NOT EXISTS almfrje_persons_livename_key
          ON public.almfrje_persons (father_id, replace(translate(lower(name), 'أإآىةؤئ', 'ااايهوي'), ' ', ''))
          WHERE status = 'alive' AND father_id IS NOT NULL;
      EXCEPTION WHEN others THEN NULL; END $func$;

      -- ربط جذر الفرع بالأشخاص
      DO $func$ BEGIN
        ALTER TABLE public.almfrje_branches
          ADD CONSTRAINT almfrje_branches_root_fk
          FOREIGN KEY (root_id) REFERENCES public.almfrje_persons(id) ON DELETE SET NULL;
      EXCEPTION WHEN duplicate_object THEN null; END $func$;

      -- 4) الوثائق والصور
      CREATE TABLE IF NOT EXISTS public.almfrje_documents (
        id          bigint generated always as identity primary key,
        person_id   bigint not null references public.almfrje_persons(id) on delete cascade,
        kind        text not null default 'doc' check (kind in ('photo','pdf','doc')),
        url text not null, label text default '',
        created_at  timestamptz not null default now(),
        created_by  uuid default auth.uid());
      CREATE INDEX IF NOT EXISTS almfrje_documents_person_idx ON public.almfrje_documents(person_id);
      ALTER TABLE public.almfrje_documents ALTER COLUMN id SET GENERATED BY DEFAULT;

      -- 5) الإعدادات
      CREATE TABLE IF NOT EXISTS public.almfrje_settings (
        key text primary key, value jsonb, updated_at timestamptz not null default now());

      -- 6) سلة المحذوفات
      CREATE TABLE IF NOT EXISTS public.almfrje_trash (
        id bigint generated always as identity primary key,
        tbl text not null, rec_id bigint, action text not null, label text default '',
        data jsonb not null, actor uuid default auth.uid(), actor_name text default '',
        created_at timestamptz not null default now());

      -- 6أ) سجل التعديلات (من أضاف/عدّل/حذف اسماً ومتى)
      CREATE TABLE IF NOT EXISTS public.almfrje_audit (
        id bigint generated always as identity primary key,
        action text not null,            -- add | edit | delete
        person_id bigint,
        person_name text default '',
        actor_name text default '',
        actor uuid default auth.uid(),
        created_at timestamptz not null default now());
      CREATE INDEX IF NOT EXISTS almfrje_audit_created_idx ON public.almfrje_audit(created_at desc);
      -- بيانات التراجع المضمّنة في السجل (للتراجع لاحقاً من سجل التعديلات)
      ALTER TABLE public.almfrje_audit ADD COLUMN IF NOT EXISTS undo_data jsonb;
      ALTER TABLE public.almfrje_audit ADD COLUMN IF NOT EXISTS undone boolean not null default false;
      ALTER TABLE public.almfrje_audit ADD COLUMN IF NOT EXISTS undone_at timestamptz;
      ALTER TABLE public.almfrje_audit ADD COLUMN IF NOT EXISTS undone_by text default '';

      -- 6ب) سجل النسخ الاحتياطية المحفوظة في القاعدة (يطلبها المدير في أي وقت)
      CREATE TABLE IF NOT EXISTS public.almfrje_backups (
        id bigint generated always as identity primary key,
        label text default '', note text default '',
        payload jsonb not null,
        persons_count int default 0, branches_count int default 0,
        actor_name text default '',
        created_at timestamptz not null default now());
      CREATE INDEX IF NOT EXISTS almfrje_backups_created_idx ON public.almfrje_backups(created_at desc);

      -- 7) دوال الصلاحية
      CREATE OR REPLACE FUNCTION public.almfrje_role() RETURNS text
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select role from public.almfrje_members where user_id = auth.uid() and is_active; $func$;
      CREATE OR REPLACE FUNCTION public.almfrje_is_member() RETURNS boolean
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select exists (select 1 from public.almfrje_members where user_id = auth.uid() and is_active); $func$;
      CREATE OR REPLACE FUNCTION public.almfrje_is_admin() RETURNS boolean
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select exists (select 1 from public.almfrje_members where user_id = auth.uid() and is_active and role = 'admin'); $func$;
      -- مشرف (فرع أو عام): الدوران المخوّلان بالإضافة والتعديل ضمن نطاقهما
      CREATE OR REPLACE FUNCTION public.almfrje_is_supervisor() RETURNS boolean
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select exists (select 1 from public.almfrje_members where user_id = auth.uid() and is_active and role in ('branch_manager','general_manager')); $func$;
      CREATE OR REPLACE FUNCTION public.almfrje_my_branch() RETURNS bigint
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select branch_id from public.almfrje_members where user_id = auth.uid() and is_active limit 1; $func$;
      -- هل يُشرف المستخدم الحالي على هذا الفرع؟ (يدعم branch_id المفرد + مصفوفة branch_ids)
      -- المشرف العام بلا فروعٍ محدّدة = يشرف على كل الفروع.
      -- مهم: عناصر branch_ids تُخزَّن أرقاماً jsonb، ومعامل ? لا يطابق إلا النصوص —
      -- لذا نفحص بـ @> للأرقام وبـ ? للنصوص (توافقاً مع أي بياناتٍ قديمة).
      CREATE OR REPLACE FUNCTION public.almfrje_manages_branch(bid bigint) RETURNS boolean
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select exists (
          select 1 from public.almfrje_members m
           where m.user_id = auth.uid() and m.is_active
             and ((m.role = 'general_manager' and m.branch_id is null and (m.branch_ids is null or m.branch_ids = '[]'::jsonb))
                  or m.branch_id = bid
                  or (m.branch_ids @> to_jsonb(bid))
                  or (m.branch_ids ? bid::text))); $func$;
      CREATE OR REPLACE FUNCTION public.almfrje_perm(act text) RETURNS boolean
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select public.almfrje_is_admin() or exists (
          select 1 from public.almfrje_members where user_id = auth.uid() and is_active
            and coalesce((perms ->> act)::boolean, false)); $func$;
      -- الجميع (الأعضاء المفعّلون) يرون كامل الشجرة؛ التقييد على التعديل لا العرض.
      CREATE OR REPLACE FUNCTION public.almfrje_can_see_person(pid bigint) RETURNS boolean
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select public.almfrje_is_member(); $func$;
      CREATE OR REPLACE FUNCTION public.almfrje_can_edit_person(pid bigint) RETURNS boolean
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select public.almfrje_is_admin() or (public.almfrje_is_supervisor() and public.almfrje_perm('info') and exists (
          select 1 from public.almfrje_persons p where p.id = pid and public.almfrje_manages_branch(p.branch_id))); $func$;
      CREATE OR REPLACE FUNCTION public.almfrje_descendant_ids(root bigint) RETURNS table(id bigint)
        LANGUAGE sql STABLE AS $func$
        with recursive d as (
          select p.id from public.almfrje_persons p where p.father_id = root
          union all
          select c.id from public.almfrje_persons c join d on c.father_id = d.id
        ) select id from d; $func$;

      -- مسح كل الأشخاص — للمدير فقط، عبر دالة محمية (لأن DELETE المباشر ممنوع للجميع).
      -- يُستخدم حصراً في «استعادة نسخة احتياطية» (استبدال كامل) — لا حذف فردي للأسماء.
      CREATE OR REPLACE FUNCTION public.almfrje_admin_wipe_persons() RETURNS void
        LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $func$
      begin
        if not public.almfrje_is_admin() then raise exception 'للمدير فقط'; end if;
        delete from public.almfrje_documents where true;
        update public.almfrje_branches set root_id = null where true;
        delete from public.almfrje_branches where true;
        delete from public.almfrje_persons where true;
      end; $func$;
      REVOKE ALL ON FUNCTION public.almfrje_admin_wipe_persons() FROM public;
      GRANT EXECUTE ON FUNCTION public.almfrje_admin_wipe_persons() TO authenticated;

      -- بحث عام بالأسماء (للعموم عند فتح الموقع للجميع) — يعيد الاسم وسلسلة النسب فقط،
      -- بلا أي بيانات حسّاسة (جوال/بريد/مدينة). يعمل فقط إذا كان public_open = true.
      CREATE OR REPLACE FUNCTION public.almfrje_public_search(q text)
        RETURNS table(id bigint, name text, lineage text)
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        with recursive cfg as (
          select coalesce((select (value)::text = 'true' from public.almfrje_settings where key = 'public_open'), false) as open
        ),
        recursive_anc as (
          select p.id, p.name, p.father_id, p.name::text as chain, 1 as depth
            from public.almfrje_persons p
           where (select open from cfg)
             and length(coalesce(q,'')) >= 2
             and p.name ilike '%' || q || '%'
          union all
          select ra.id, ra.name, f.father_id, ra.chain || ' بن ' || f.name, ra.depth + 1
            from recursive_anc ra
            join public.almfrje_persons f on f.id = ra.father_id
           where ra.depth < 12
        )
        select distinct on (id) id, name, chain as lineage
          from recursive_anc
         order by id, depth desc
         limit 50; $func$;
      REVOKE ALL ON FUNCTION public.almfrje_public_search(text) FROM public;
      GRANT EXECUTE ON FUNCTION public.almfrje_public_search(text) TO anon, authenticated;

      -- 8) إنشاء العضو تلقائياً — أوّل مَن يسجّل يصبح مديراً مفعّلاً (بلا تدخّل يدوي)
      CREATE OR REPLACE FUNCTION public.almfrje_handle_new_user() RETURNS trigger
        LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $func$
      declare _first boolean;
      begin
        select not exists (select 1 from public.almfrje_members) into _first;
        begin
          insert into public.almfrje_members (user_id, full_name, username, phone, role, is_active, perms)
          values (new.id,
                  coalesce(new.raw_user_meta_data->>'full_name', ''),
                  nullif(new.raw_user_meta_data->>'username', ''),
                  nullif(new.raw_user_meta_data->>'phone', ''),
                  case when _first then 'admin' else 'viewer' end,
                  _first, '{}'::jsonb)
          on conflict (user_id) do nothing;
        exception when others then null;  -- لا تُفشل التسجيل مهما حدث
        end;
        return new;
      end; $func$;
      DROP TRIGGER IF EXISTS on_auth_user_created_almfrje ON auth.users;
      CREATE TRIGGER on_auth_user_created_almfrje AFTER INSERT ON auth.users
        FOR EACH ROW EXECUTE FUNCTION public.almfrje_handle_new_user();

      -- استرجاع بريد الدخول من الجوال أو اسم المستخدم
      CREATE OR REPLACE FUNCTION public.almfrje_resolve_login(ident text) RETURNS text
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, auth AS $func$
        select u.email from public.almfrje_members m join auth.users u on u.id = m.user_id
         where m.phone = ident or lower(m.username) = lower(ident)
         order by (m.phone = ident) desc limit 1; $func$;
      REVOKE ALL ON FUNCTION public.almfrje_resolve_login(text) FROM public;
      GRANT EXECUTE ON FUNCTION public.almfrje_resolve_login(text) TO anon, authenticated;

      -- تبنّي صلاحية المدير: أوّل مستخدم يطلبها يصبح مديراً ما لم يوجد مديرٌ مفعّل بعد.
      -- يعالج حالة «بانتظار التفعيل» للمستخدم الأول (تجاوز فخّ التهيئة) — آمن لأنه
      -- يرفض الترقية فور وجود مدير مفعّل واحد.
      CREATE OR REPLACE FUNCTION public.almfrje_claim_admin() RETURNS text
        LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $func$
      declare _uid uuid := auth.uid(); _has_admin boolean;
      begin
        if _uid is null then return 'unauthenticated'; end if;
        select exists (select 1 from public.almfrje_members where is_active and role = 'admin') into _has_admin;
        if _has_admin then return 'exists'; end if;
        insert into public.almfrje_members (user_id, role, is_active, perms)
          values (_uid, 'admin', true, '{}'::jsonb)
          on conflict (user_id) do update set role = 'admin', is_active = true;
        return 'claimed';
      end; $func$;
      REVOKE ALL ON FUNCTION public.almfrje_claim_admin() FROM public;
      GRANT EXECUTE ON FUNCTION public.almfrje_claim_admin() TO authenticated;

      -- تفعيل حساب الزائر المدمج (للتصفّح بلا تسجيل): يُفعّل دور «viewer» فقط للحساب
      -- المخصّص (guest@almfrje.app) ولا يمنح أي صلاحية أعلى مهما حدث.
      CREATE OR REPLACE FUNCTION public.almfrje_ensure_guest() RETURNS text
        LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth AS $func$
      declare _uid uuid := auth.uid(); _email text;
      begin
        if _uid is null then return 'unauthenticated'; end if;
        select email into _email from auth.users where id = _uid;
        if _email is distinct from 'guest@almfrje.app' then return 'not_guest'; end if;
        insert into public.almfrje_members (user_id, full_name, role, is_active, perms)
          values (_uid, 'زائر', 'viewer', true, '{}'::jsonb)
          on conflict (user_id) do update set role = 'viewer', is_active = true, full_name = 'زائر';
        return 'ok';
      end; $func$;
      REVOKE ALL ON FUNCTION public.almfrje_ensure_guest() FROM public;
      GRANT EXECUTE ON FUNCTION public.almfrje_ensure_guest() TO authenticated;

      -- 9) تفعيل RLS
      ALTER TABLE public.almfrje_branches  ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.almfrje_members   ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.almfrje_persons   ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.almfrje_documents ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.almfrje_settings  ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.almfrje_trash     ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.almfrje_audit     ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.almfrje_backups   ENABLE ROW LEVEL SECURITY;

      -- الأعضاء
      DROP POLICY IF EXISTS members_select ON public.almfrje_members; CREATE POLICY members_select ON public.almfrje_members FOR SELECT USING (public.almfrje_is_member() or user_id = auth.uid());
      DROP POLICY IF EXISTS members_insert ON public.almfrje_members; CREATE POLICY members_insert ON public.almfrje_members FOR INSERT WITH CHECK (public.almfrje_is_admin());
      DROP POLICY IF EXISTS members_update ON public.almfrje_members; CREATE POLICY members_update ON public.almfrje_members FOR UPDATE USING (public.almfrje_is_admin()) WITH CHECK (public.almfrje_is_admin());
      DROP POLICY IF EXISTS members_delete ON public.almfrje_members; CREATE POLICY members_delete ON public.almfrje_members FOR DELETE USING (public.almfrje_is_admin() and user_id <> auth.uid());
      -- الفروع
      DROP POLICY IF EXISTS branches_select ON public.almfrje_branches; CREATE POLICY branches_select ON public.almfrje_branches FOR SELECT USING (public.almfrje_is_member());
      DROP POLICY IF EXISTS branches_ins ON public.almfrje_branches; CREATE POLICY branches_ins ON public.almfrje_branches FOR INSERT WITH CHECK (public.almfrje_is_admin());
      DROP POLICY IF EXISTS branches_upd ON public.almfrje_branches; CREATE POLICY branches_upd ON public.almfrje_branches FOR UPDATE USING (public.almfrje_is_admin()) WITH CHECK (public.almfrje_is_admin());
      DROP POLICY IF EXISTS branches_del ON public.almfrje_branches; CREATE POLICY branches_del ON public.almfrje_branches FOR DELETE USING (public.almfrje_is_admin());
      -- الأشخاص
      DROP POLICY IF EXISTS persons_sel ON public.almfrje_persons; CREATE POLICY persons_sel ON public.almfrje_persons FOR SELECT USING (public.almfrje_is_member());
      -- إضافة مواليد: مسؤول الفرع يضيف ضمن فروعه فقط، بشرط أن يكون والد المولود
      -- نفسه ضمن فرع يديره (لا يكفي تطابق branch_id المُرسَل — نتحقّق من الأب فعلياً).
      DROP POLICY IF EXISTS persons_ins ON public.almfrje_persons; CREATE POLICY persons_ins ON public.almfrje_persons FOR INSERT WITH CHECK (
        public.almfrje_is_admin() or (
          public.almfrje_is_supervisor()
          and public.almfrje_manages_branch(branch_id)
          and father_id is not null
          and exists (select 1 from public.almfrje_persons f
                       where f.id = father_id and public.almfrje_manages_branch(f.branch_id))
        ));
      -- التعديل للمدير فقط (ما يضيفه مسؤول الفرع لا يعدّله إلا المدير)
      -- التعديل: المدير على الكل، ومسؤول الفرع ضمن فروعه المصرّح له بها فقط (لا يتجاوزها)
      DROP POLICY IF EXISTS persons_upd ON public.almfrje_persons; CREATE POLICY persons_upd ON public.almfrje_persons FOR UPDATE USING (public.almfrje_is_admin() or (public.almfrje_is_supervisor() and public.almfrje_manages_branch(branch_id))) WITH CHECK (public.almfrje_is_admin() or (public.almfrje_is_supervisor() and public.almfrje_manages_branch(branch_id)));
      -- الحذف للمدير فقط
      -- حذف الأسماء منتهٍ نهائياً لأي مستخدم (قرار المالك). لا حذف عبر الواجهة ولا API.
      DROP POLICY IF EXISTS persons_del ON public.almfrje_persons; CREATE POLICY persons_del ON public.almfrje_persons FOR DELETE USING (false);
      -- الوثائق
      DROP POLICY IF EXISTS docs_sel ON public.almfrje_documents; CREATE POLICY docs_sel ON public.almfrje_documents FOR SELECT USING (public.almfrje_can_see_person(person_id));
      DROP POLICY IF EXISTS docs_ins ON public.almfrje_documents; CREATE POLICY docs_ins ON public.almfrje_documents FOR INSERT WITH CHECK (public.almfrje_can_edit_person(person_id));
      DROP POLICY IF EXISTS docs_del ON public.almfrje_documents; CREATE POLICY docs_del ON public.almfrje_documents FOR DELETE USING (public.almfrje_can_edit_person(person_id) or public.almfrje_is_admin());
      -- الإعدادات
      DROP POLICY IF EXISTS settings_sel ON public.almfrje_settings; CREATE POLICY settings_sel ON public.almfrje_settings FOR SELECT USING (true);
      DROP POLICY IF EXISTS settings_ins ON public.almfrje_settings; CREATE POLICY settings_ins ON public.almfrje_settings FOR INSERT WITH CHECK (public.almfrje_is_admin());
      DROP POLICY IF EXISTS settings_upd ON public.almfrje_settings; CREATE POLICY settings_upd ON public.almfrje_settings FOR UPDATE USING (public.almfrje_is_admin()) WITH CHECK (public.almfrje_is_admin());
      -- سلة المحذوفات
      DROP POLICY IF EXISTS trash_sel ON public.almfrje_trash; CREATE POLICY trash_sel ON public.almfrje_trash FOR SELECT USING (public.almfrje_is_admin());
      DROP POLICY IF EXISTS trash_ins ON public.almfrje_trash; CREATE POLICY trash_ins ON public.almfrje_trash FOR INSERT WITH CHECK (public.almfrje_is_member());
      DROP POLICY IF EXISTS trash_del ON public.almfrje_trash; CREATE POLICY trash_del ON public.almfrje_trash FOR DELETE USING (public.almfrje_is_admin());
      -- سجل التعديلات: أي عضو يسجّل، المدير يعرض الكل ويحذف، ومسؤول الفرع يعرض أفعاله فقط
      DROP POLICY IF EXISTS audit_sel ON public.almfrje_audit; CREATE POLICY audit_sel ON public.almfrje_audit FOR SELECT USING (public.almfrje_is_admin() OR actor = auth.uid());
      DROP POLICY IF EXISTS audit_ins ON public.almfrje_audit; CREATE POLICY audit_ins ON public.almfrje_audit FOR INSERT WITH CHECK (public.almfrje_is_member());
      DROP POLICY IF EXISTS audit_del ON public.almfrje_audit; CREATE POLICY audit_del ON public.almfrje_audit FOR DELETE USING (public.almfrje_is_admin());
      DROP POLICY IF EXISTS audit_upd ON public.almfrje_audit; CREATE POLICY audit_upd ON public.almfrje_audit FOR UPDATE USING (public.almfrje_is_member()) WITH CHECK (public.almfrje_is_member());
      -- النسخ الاحتياطية: للمدير فقط (إنشاء/عرض/حذف)
      DROP POLICY IF EXISTS bkp_sel ON public.almfrje_backups; CREATE POLICY bkp_sel ON public.almfrje_backups FOR SELECT USING (public.almfrje_is_admin());
      DROP POLICY IF EXISTS bkp_ins ON public.almfrje_backups; CREATE POLICY bkp_ins ON public.almfrje_backups FOR INSERT WITH CHECK (public.almfrje_is_admin());
      DROP POLICY IF EXISTS bkp_del ON public.almfrje_backups; CREATE POLICY bkp_del ON public.almfrje_backups FOR DELETE USING (public.almfrje_is_admin());

      GRANT SELECT ON public.almfrje_settings TO anon, authenticated;

      -- ختم إصدار المخطط: يرتفع مع كل تعديلٍ للمخطط، ووجوده بالقيمة الأحدث في القاعدة
      -- دليلٌ قاطع أن قناة الترقية التلقائية (/api/almfrje-setup) تعمل.
      INSERT INTO public.almfrje_settings (key, value)
        VALUES ('schema_rev', '"2026-07-06-8"'::jsonb)
        ON CONFLICT (key) DO UPDATE SET value = '"2026-07-06-8"'::jsonb, updated_at = now();

      -- ملاحظات الزوار: يرسلها أي زائر/عضو، ويراجعها المدير ويضع علامة «تم».
      CREATE TABLE IF NOT EXISTS public.almfrje_feedback (
        id bigint generated always as identity primary key,
        subject text not null,
        branch_id bigint references public.almfrje_branches(id) on delete set null,
        details text default '',
        error_desc text default '',
        status text not null default 'new' check (status in ('new','done')),
        created_by uuid default auth.uid(),
        created_by_name text default '',
        done_by_name text default '',
        done_at timestamptz,
        created_at timestamptz not null default now()
      );
      -- ردّ الإدارة على الملاحظة (يظهر للمرسل باسم «الإدارة»؛ اسم الرادّ يُحفظ داخلياً)
      ALTER TABLE public.almfrje_feedback ADD COLUMN IF NOT EXISTS reply text default '';
      ALTER TABLE public.almfrje_feedback ADD COLUMN IF NOT EXISTS replied_by_name text default '';
      ALTER TABLE public.almfrje_feedback ADD COLUMN IF NOT EXISTS replied_at timestamptz;
      -- جوال المرسل (للتواصل والتحقق) وربط شخصه في الشجرة (لإضافة الجوال لملفه بعد التحقق)
      ALTER TABLE public.almfrje_feedback ADD COLUMN IF NOT EXISTS sender_phone text default '';
      ALTER TABLE public.almfrje_feedback ADD COLUMN IF NOT EXISTS sender_person_id bigint;
      -- هل قرأ المرسل الرد؟ (يُصفَّر عند كل ردٍّ جديد/معدَّل فتنبثق الرسالة له عند دخوله)
      ALTER TABLE public.almfrje_feedback ADD COLUMN IF NOT EXISTS reply_seen boolean not null default false;
      ALTER TABLE public.almfrje_feedback ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS feedback_ins ON public.almfrje_feedback; CREATE POLICY feedback_ins ON public.almfrje_feedback FOR INSERT WITH CHECK (true);
      -- المدير يرى كل الملاحظات؛ ومسؤول الفرع يرى/يعالج «إضافة مولود» و«ملاحظة» ضمن فروعه فقط (للموافقة/الإجراء).
      DROP POLICY IF EXISTS feedback_sel ON public.almfrje_feedback; CREATE POLICY feedback_sel ON public.almfrje_feedback FOR SELECT USING (public.almfrje_is_admin() OR (subject in ('إضافة مولود','ملاحظة','إعادة ترتيب الإخوان') AND public.almfrje_is_supervisor() AND public.almfrje_manages_branch(branch_id)));
      DROP POLICY IF EXISTS feedback_upd ON public.almfrje_feedback; CREATE POLICY feedback_upd ON public.almfrje_feedback FOR UPDATE USING (public.almfrje_is_admin() OR (subject in ('إضافة مولود','ملاحظة','إعادة ترتيب الإخوان') AND public.almfrje_is_supervisor() AND public.almfrje_manages_branch(branch_id))) WITH CHECK (public.almfrje_is_admin() OR (subject in ('إضافة مولود','ملاحظة','إعادة ترتيب الإخوان') AND public.almfrje_is_supervisor() AND public.almfrje_manages_branch(branch_id)));
      DROP POLICY IF EXISTS feedback_del ON public.almfrje_feedback; CREATE POLICY feedback_del ON public.almfrje_feedback FOR DELETE USING (public.almfrje_is_admin() OR (subject in ('إضافة مولود','ملاحظة','إعادة ترتيب الإخوان') AND public.almfrje_is_supervisor() AND public.almfrje_manages_branch(branch_id)));
      GRANT INSERT ON public.almfrje_feedback TO anon, authenticated;
      GRANT SELECT, UPDATE, DELETE ON public.almfrje_feedback TO authenticated;

      -- 11) المناقشات (للمدير والمشرفين العامين فقط) — كل موضوعٍ نقاشه مستقل كمحادثة واتساب
      CREATE TABLE IF NOT EXISTS public.almfrje_topics (
        id bigint generated by default as identity primary key,
        title text not null,
        created_by uuid default auth.uid(),
        created_by_name text default '',
        created_at timestamptz not null default now(),
        last_msg_at timestamptz not null default now(),
        last_msg_text text default '',
        last_msg_by text default ''
      );
      CREATE TABLE IF NOT EXISTS public.almfrje_topic_msgs (
        id bigint generated by default as identity primary key,
        topic_id bigint not null references public.almfrje_topics(id) on delete cascade,
        body text not null,
        author uuid default auth.uid(),
        author_name text default '',
        created_at timestamptz not null default now()
      );
      CREATE INDEX IF NOT EXISTS almfrje_topic_msgs_topic_idx ON public.almfrje_topic_msgs(topic_id, id);
      CREATE TABLE IF NOT EXISTS public.almfrje_topic_reads (
        user_id uuid not null,
        topic_id bigint not null references public.almfrje_topics(id) on delete cascade,
        last_read_at timestamptz not null default now(),
        primary key (user_id, topic_id)
      );
      -- صلاحية المناقشات: مدير النظام أو مشرف عام (مفعّل)
      CREATE OR REPLACE FUNCTION public.almfrje_can_discuss() RETURNS boolean
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $func$
        select exists (select 1 from public.almfrje_members where user_id = auth.uid() and is_active and role in ('admin','general_manager')); $func$;
      ALTER TABLE public.almfrje_topics      ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.almfrje_topic_msgs  ENABLE ROW LEVEL SECURITY;
      ALTER TABLE public.almfrje_topic_reads ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS topics_sel ON public.almfrje_topics; CREATE POLICY topics_sel ON public.almfrje_topics FOR SELECT USING (public.almfrje_can_discuss());
      DROP POLICY IF EXISTS topics_ins ON public.almfrje_topics; CREATE POLICY topics_ins ON public.almfrje_topics FOR INSERT WITH CHECK (public.almfrje_can_discuss());
      DROP POLICY IF EXISTS topics_upd ON public.almfrje_topics; CREATE POLICY topics_upd ON public.almfrje_topics FOR UPDATE USING (public.almfrje_can_discuss()) WITH CHECK (public.almfrje_can_discuss());
      DROP POLICY IF EXISTS topics_del ON public.almfrje_topics; CREATE POLICY topics_del ON public.almfrje_topics FOR DELETE USING (public.almfrje_is_admin());
      DROP POLICY IF EXISTS tmsgs_sel ON public.almfrje_topic_msgs; CREATE POLICY tmsgs_sel ON public.almfrje_topic_msgs FOR SELECT USING (public.almfrje_can_discuss());
      DROP POLICY IF EXISTS tmsgs_ins ON public.almfrje_topic_msgs; CREATE POLICY tmsgs_ins ON public.almfrje_topic_msgs FOR INSERT WITH CHECK (public.almfrje_can_discuss());
      DROP POLICY IF EXISTS tmsgs_del ON public.almfrje_topic_msgs; CREATE POLICY tmsgs_del ON public.almfrje_topic_msgs FOR DELETE USING (public.almfrje_is_admin());
      DROP POLICY IF EXISTS treads_sel ON public.almfrje_topic_reads; CREATE POLICY treads_sel ON public.almfrje_topic_reads FOR SELECT USING (user_id = auth.uid());
      DROP POLICY IF EXISTS treads_ins ON public.almfrje_topic_reads; CREATE POLICY treads_ins ON public.almfrje_topic_reads FOR INSERT WITH CHECK (user_id = auth.uid() and public.almfrje_can_discuss());
      DROP POLICY IF EXISTS treads_upd ON public.almfrje_topic_reads; CREATE POLICY treads_upd ON public.almfrje_topic_reads FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
      GRANT SELECT, INSERT, UPDATE, DELETE ON public.almfrje_topics, public.almfrje_topic_msgs, public.almfrje_topic_reads TO authenticated;

      -- 10) تحصين الخصوصية والنزاهة (يُطبَّق فوق ما سبق) =================
      -- منظور منقّى للأشخاص بلا بيانات حسّاسة (جوال/بريد/ملاحظات) — للزائر/المطّلع.
      CREATE OR REPLACE VIEW public.almfrje_persons_pub AS
        SELECT id, name, father_id, branch_id, generation, sex, status,
               birth, death, city, photo_url, nickname, work, sort,
               created_at, created_by_name, updated_by_name, updated_at, field_audit
          FROM public.almfrje_persons;
      GRANT SELECT ON public.almfrje_persons_pub TO authenticated;
      REVOKE SELECT ON public.almfrje_persons_pub FROM anon;

      -- الجدول الكامل (يحوي الجوال/البريد/الملاحظات) للمدير ومشرف الفرع فقط؛ الزائر يقرأ المنظور.
      DROP POLICY IF EXISTS persons_sel ON public.almfrje_persons;
      CREATE POLICY persons_sel ON public.almfrje_persons FOR SELECT
        USING (public.almfrje_is_admin() OR public.almfrje_is_supervisor());

      -- الأعضاء: المدير يرى الكل، وغيره صفّه فقط (إخفاء جوالات الآخرين عن الزائر).
      DROP POLICY IF EXISTS members_select ON public.almfrje_members;
      CREATE POLICY members_select ON public.almfrje_members FOR SELECT
        USING (public.almfrje_is_admin() OR user_id = auth.uid());

      -- سجل التعديلات: العضو يكتب/يعدّل صفوفه فقط، والمدير الكل (منع العبث بسجلّ الغير).
      DROP POLICY IF EXISTS audit_ins ON public.almfrje_audit;
      CREATE POLICY audit_ins ON public.almfrje_audit FOR INSERT WITH CHECK (actor = auth.uid());
      DROP POLICY IF EXISTS audit_upd ON public.almfrje_audit;
      CREATE POLICY audit_upd ON public.almfrje_audit FOR UPDATE
        USING (public.almfrje_is_admin() OR actor = auth.uid())
        WITH CHECK (public.almfrje_is_admin() OR actor = auth.uid());
`;
